import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Fernando',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Kleber',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Lacoste shoes sneakers ola',
      category: 'Sneakers',
      image: '/images/product-1.png',
      price: 119.90,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'Sneakers Adidas color black extremely comfortable and ready for the day-to-day.',
    },
    {
      name: 'Yellow shoes ola',
      category: 'Sneakers',
      image: '/images/nike-white.png',
      price: 99.90,
      countInStock: 20,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 10,
      description: 'White sneakers Nike made for hanging outs.',
    },
    {
      name: 'Green shoes ola',
      category: 'Sneakers',
      image: '/images/nike-black.png',
      price: 199.90,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'Black Nike Shoes for you to practice your daily exercises.',
    },
    {
      name: 'Red Shoes ola',
      category: 'Shoes',
      image: '/images/product-1.png',
      price: 120.9,
      countInStock: 15,
      brand: 'Lacoste',
      rating: 3.5,
      numReviews: 10,
      description: 'Sneakers Nike color black extremely comfortable.',
    },
    {
      name: 'Brown Sneaker ola',
      category: 'Sneakers',
      image: '/images/nike-black.png',
      price: 120.9,
      countInStock: 5,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 10,
      description: 'Sneakers Nike color black extremely comfortable.',
    },
    {
      name: 'Purple Sneakers ola',
      category: 'Sneakers',
      image: '/images/nike-white.png',
      price: 120.9,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'Sneakers Nike color black extremely comfortable.',
    },
  ],
};

export default data;