const data = {
  products: [
    {
      _id: '1',
      name: 'Adidas Sneakers Black',
      category: 'Sneakers',
      image: '/images/product-1.png',
      price: 119.90,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'Sneakers Adidas color black extremely comfortable and ready for the day-to-day.',
    },
    {
      _id: '2',
      name: 'White Nike Sneakers',
      category: 'Sneakers',
      image: '/images/nike-white.png',
      price: 99.90,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 10,
      description: 'White sneakers Nike made for hanging outs.',
    },
    {
      _id: '3',
      name: 'Nike shoes',
      category: 'Sneakers',
      image: '/images/nike-black.png',
      price: 199.90,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'Black Nike Shoes for you to practice your daily exercises.',
    },
    {
      _id: '4',
      name: 'Lacoste Shoes',
      category: 'Shoes',
      image: '/images/product-1.png',
      price: 120.9,
      brand: 'Lacoste',
      rating: 3.5,
      numReviews: 10,
      description: 'Sneakers Nike color black extremely comfortable.',
    },
    {
      _id: '5',
      name: 'Adidas Sneakers Black',
      category: 'Sneakers',
      image: '/images/nike-black.png',
      price: 120.9,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 10,
      description: 'Sneakers Nike color black extremely comfortable.',
    },
    {
      _id: '6',
      name: 'Adidas Sneakers Black',
      category: 'Sneakers',
      image: '/images/nike-white.png',
      price: 120.9,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'Sneakers Nike color black extremely comfortable.',
    },
  ],
};

export default data;